<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>4.0.0</Version>
    <Description>Générateur de modèle TopModel à partir de sources externes (OpenAPI, Postgresql, Oracle...).</Description>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>tmdgen</ToolCommandName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Microsoft.OpenApi.YamlReader" />
    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TopModel.Utils.Cli\TopModel.Utils.Cli.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="schema.tmdgen.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
