<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Castle.Core" Version="5.2.1" />
    <PackageVersion Include="Dapper" Version="2.1.72" />
    <PackageVersion Include="Kinetix.Tools.Analyzers" Version="1.11.6" />
    <PackageVersion Include="JsonSchema.Net" Version="9.2.0" />
    <PackageVersion Include="Meziantou.Analyzer" Version="3.0.52" />
    <PackageVersion Include="Meziantou.Framework.Globbing" Version="2.1.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.7" />
    <PackageVersion Include="Microsoft.OpenApi.YamlReader" Version="3.5.2" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.203" />
    <PackageVersion Include="MySqlConnector" Version="2.5.0" />
    <PackageVersion Include="NeoSmart.AsyncLock" Version="3.2.1" />
    <PackageVersion Include="Npgsql" Version="10.0.2" />
    <PackageVersion Include="NuGet.Commands" Version="7.3.1" />
    <PackageVersion Include="OmniSharp.Extensions.LanguageServer" Version="0.19.9" />
    <PackageVersion Include="OneOf" Version="3.0.271" />
    <PackageVersion Include="Oracle.ManagedDataAccess.Core" Version="23.26.200" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.24.0.138807" />
    <PackageVersion Include="Spectre.Console" Version="0.55.2" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageVersion Include="System.CommandLine" Version="2.0.7" />
    <PackageVersion Include="System.Linq.Async" Version="7.0.1" />
    <PackageVersion Include="YamlDotNet" Version="17.0.1" />
  </ItemGroup>
</Project>
