<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>4.1.0</Version>
    <Description>Librarie de base pour écrire un générateur TopModel.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Castle.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TopModel.Core\TopModel.Core.csproj" />
  </ItemGroup>
</Project>
