// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TopModel.Sample.Clients.Db;

#nullable disable

namespace TopModel.Sample.Api.Migrations
{
    [DbContext(typeof(TopModelSampleDbContext))]
    partial class TopModelSampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("seq_vaisselle");

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Common.Translation", b =>
                {
                    b.Property<string>("ResourceKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tra_resource_key")
                        .HasComment("Clé de traduction.");

                    b.Property<string>("Lang")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tra_lang")
                        .HasComment("Langue de traduction");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tra_value")
                        .HasComment("Valeur de la clé de traduction.");

                    b.HasKey("ResourceKey", "Lang");

                    b.HasIndex("ResourceKey");

                    b.ToTable("translation", t =>
                        {
                            t.HasComment("Table pour stocker les traductions en SQL.");
                        });

                    b.HasData(
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Autre",
                            Lang = "fr",
                            Value = "Autre"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Boisson",
                            Lang = "fr",
                            Value = "Boisson"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Dessert",
                            Lang = "fr",
                            Value = "Dessert"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Entree",
                            Lang = "fr",
                            Value = "Entrée"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Principal",
                            Lang = "fr",
                            Value = "Plat principal"
                        },
                        new
                        {
                            ResourceKey = "restaurant.departement.values.HautsDeSeine",
                            Lang = "fr",
                            Value = "Hauts de Seine"
                        },
                        new
                        {
                            ResourceKey = "restaurant.departement.values.Paris",
                            Lang = "fr",
                            Value = "Paris"
                        },
                        new
                        {
                            ResourceKey = "restaurant.departement.values.SeineEtMarne",
                            Lang = "fr",
                            Value = "Seine et Marne"
                        },
                        new
                        {
                            ResourceKey = "restaurant.departement.values.SeineSaintDenis",
                            Lang = "fr",
                            Value = "Seine Saint Denis"
                        },
                        new
                        {
                            ResourceKey = "restaurant.region.values.Idf",
                            Lang = "fr",
                            Value = "Île de France"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.Annulee",
                            Lang = "fr",
                            Value = "Annulée"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.EnAttente",
                            Lang = "fr",
                            Value = "En attente"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.EnPreparation",
                            Lang = "fr",
                            Value = "En préparation"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.Prete",
                            Lang = "fr",
                            Value = "Prête"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.Servie",
                            Lang = "fr",
                            Value = "Servie"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Autre",
                            Lang = "de",
                            Value = "Autre"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Boisson",
                            Lang = "de",
                            Value = "Boisson"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Dessert",
                            Lang = "de",
                            Value = "Dessert"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Entree",
                            Lang = "de",
                            Value = "Entrée"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Principal",
                            Lang = "de",
                            Value = "Plat principal"
                        },
                        new
                        {
                            ResourceKey = "restaurant.departement.values.HautsDeSeine",
                            Lang = "de",
                            Value = "Hauts de Seine"
                        },
                        new
                        {
                            ResourceKey = "restaurant.departement.values.Paris",
                            Lang = "de",
                            Value = "Paris"
                        },
                        new
                        {
                            ResourceKey = "restaurant.departement.values.SeineEtMarne",
                            Lang = "de",
                            Value = "Seine et Marne"
                        },
                        new
                        {
                            ResourceKey = "restaurant.departement.values.SeineSaintDenis",
                            Lang = "de",
                            Value = "Seine Saint Denis"
                        },
                        new
                        {
                            ResourceKey = "restaurant.region.values.Idf",
                            Lang = "de",
                            Value = "Île de France"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.Annulee",
                            Lang = "de",
                            Value = "Annulée"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.EnAttente",
                            Lang = "de",
                            Value = "En attente"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.EnPreparation",
                            Lang = "de",
                            Value = "En préparation"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.Prete",
                            Lang = "de",
                            Value = "Prête"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.Servie",
                            Lang = "de",
                            Value = "Servie"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Autre",
                            Lang = "en",
                            Value = "Autre"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Boisson",
                            Lang = "en",
                            Value = "Drink"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Dessert",
                            Lang = "en",
                            Value = "Dessert"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Entree",
                            Lang = "en",
                            Value = "Starter"
                        },
                        new
                        {
                            ResourceKey = "restaurant.categoriePlat.values.Principal",
                            Lang = "en",
                            Value = "Plat principal"
                        },
                        new
                        {
                            ResourceKey = "restaurant.departement.values.HautsDeSeine",
                            Lang = "en",
                            Value = "Hauts de Seine"
                        },
                        new
                        {
                            ResourceKey = "restaurant.departement.values.Paris",
                            Lang = "en",
                            Value = "Paris"
                        },
                        new
                        {
                            ResourceKey = "restaurant.departement.values.SeineEtMarne",
                            Lang = "en",
                            Value = "Seine et Marne"
                        },
                        new
                        {
                            ResourceKey = "restaurant.departement.values.SeineSaintDenis",
                            Lang = "en",
                            Value = "Seine Saint Denis"
                        },
                        new
                        {
                            ResourceKey = "restaurant.region.values.Idf",
                            Lang = "en",
                            Value = "Île de France"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.Annulee",
                            Lang = "en",
                            Value = "Cancelled"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.EnAttente",
                            Lang = "en",
                            Value = "Pending"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.EnPreparation",
                            Lang = "en",
                            Value = "In preparation"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.Prete",
                            Lang = "en",
                            Value = "Ready"
                        },
                        new
                        {
                            ResourceKey = "restaurant.statutCommande.values.Servie",
                            Lang = "en",
                            Value = "Served"
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.AvisClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("avi_id")
                        .HasComment("Identifiant de l'avis");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approuve")
                        .HasColumnType("boolean")
                        .HasColumnName("avi_approuve")
                        .HasComment("Indique si l'avis est approuvé par le restaurant");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("per_id")
                        .HasComment("Client ayant donné l'avis");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("avi_commentaire")
                        .HasComment("Commentaire de l'avis");

                    b.Property<DateTime>("DateAvis")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("avi_date_avis")
                        .HasComment("Date de l'avis");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("avi_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<int>("NombreVues")
                        .HasColumnType("integer")
                        .HasColumnName("avi_nombre_vues")
                        .HasComment("Nombre de vues de l'avis (calculé)");

                    b.Property<int>("Note")
                        .HasColumnType("integer")
                        .HasColumnName("avi_note")
                        .HasComment("Note sur 5");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("lie_id")
                        .HasComment("Restaurant concerné par l'avis");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("ClientId", "RestaurantId", "DateAvis")
                        .IsUnique();

                    b.ToTable("avis_client", t =>
                        {
                            t.HasComment("Avis d'un client sur un restaurant");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.CategoriePlatRegion", b =>
                {
                    b.Property<string>("RegionCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reg_code")
                        .HasComment("Région");

                    b.Property<string>("CategoriePlatCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cat_code")
                        .HasComment("Catégorie de plat");

                    b.HasKey("RegionCode", "CategoriePlatCode");

                    b.HasIndex("CategoriePlatCode");

                    b.ToTable("categorie_plat_region", t =>
                        {
                            t.HasComment("Catégories de plats disponibles par région");
                        });

                    b.HasData(
                        new
                        {
                            RegionCode = "IDF",
                            CategoriePlatCode = "ENTREE"
                        },
                        new
                        {
                            RegionCode = "IDF",
                            CategoriePlatCode = "DESSERT"
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("com_id")
                        .HasComment("Identifiant de la commande");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvisClientId")
                        .HasColumnType("integer")
                        .HasColumnName("avi_id")
                        .HasComment("Avis laissé par le client sur la commande.");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("per_id")
                        .HasComment("Client ayant passé la commande");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("com_date_commande")
                        .HasComment("Date et heure de la commande");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("com_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<DateTime?>("DateLivraison")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("com_date_livraison")
                        .HasComment("Date et heure de livraison");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("com_montant_total")
                        .HasComment("Montant total de la commande");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("rev_id")
                        .HasComment("Réservation associée à la commande");

                    b.Property<string>("StatutCommande")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("stc_code")
                        .HasComment("Statut de la commande");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer")
                        .HasColumnName("tab_id")
                        .HasComment("Table associée à la commande");

                    b.HasKey("Id");

                    b.HasIndex("AvisClientId")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("TableId");

                    b.ToTable("commande", t =>
                        {
                            t.HasComment("Commande d'un client");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.CommandeHistorique", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("com_id")
                        .HasComment("Identifiant de la commande");

                    b.Property<int?>("AvisClientId")
                        .HasColumnType("integer")
                        .HasColumnName("avi_id")
                        .HasComment("Avis laissé par le client sur la commande.");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("per_id")
                        .HasComment("Client ayant passé la commande");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("com_date_commande")
                        .HasComment("Date et heure de la commande");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("com_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<DateTime?>("DateLivraison")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("com_date_livraison")
                        .HasComment("Date et heure de livraison");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("com_montant_total")
                        .HasComment("Montant total de la commande");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("rev_id")
                        .HasComment("Réservation associée à la commande");

                    b.Property<string>("StatutCommande")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("stc_code")
                        .HasComment("Statut de la commande");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer")
                        .HasColumnName("tab_id")
                        .HasComment("Table associée à la commande");

                    b.HasKey("Id");

                    b.ToTable("commande_historique", t =>
                        {
                            t.HasComment("Commande pour historique avec préservation des clés primaires");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Lieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lie_id")
                        .HasComment("Identifiant du restaurant");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lie_adresse")
                        .HasComment("Adresse du restaurant");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lie_nom")
                        .HasComment("Nom du restaurant");

                    b.Property<string>("lie_discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("lieu", t =>
                        {
                            t.HasComment("Lieu");
                        });

                    b.HasDiscriminator<string>("lie_discriminator").HasValue("Lieu");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lig_id")
                        .HasComment("Identifiant de la ligne");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer")
                        .HasColumnName("com_id")
                        .HasComment("Commande à laquelle appartient la ligne");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lig_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<int>("PlatId")
                        .HasColumnType("integer")
                        .HasColumnName("pla_id")
                        .HasComment("Plat commandé");

                    b.Property<decimal>("PrixTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("lig_prix_total")
                        .HasComment("Prix total de la ligne");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("numeric")
                        .HasColumnName("lig_prix_unitaire")
                        .HasComment("Prix unitaire au moment de la commande");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("lig_quantite")
                        .HasComment("Quantité commandée");

                    b.HasKey("Id");

                    b.HasIndex("PlatId");

                    b.HasIndex("CommandeId", "PlatId")
                        .IsUnique();

                    b.ToTable("ligne_commande", t =>
                        {
                            t.HasComment("Ligne d'une commande");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.LigneCommandeHistorique", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("lig_id")
                        .HasComment("Identifiant de la ligne");

                    b.Property<int>("CommandeHistoriqueId")
                        .HasColumnType("integer")
                        .HasColumnName("com_id")
                        .HasComment("Commande à laquelle appartient la ligne");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lig_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<int>("PlatId")
                        .HasColumnType("integer")
                        .HasColumnName("pla_id")
                        .HasComment("Plat commandé");

                    b.Property<decimal>("PrixTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("lig_prix_total")
                        .HasComment("Prix total de la ligne");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("numeric")
                        .HasColumnName("lig_prix_unitaire")
                        .HasComment("Prix unitaire au moment de la commande");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("lig_quantite")
                        .HasComment("Quantité commandée");

                    b.HasKey("Id");

                    b.HasIndex("CommandeHistoriqueId");

                    b.ToTable("ligne_commande_historique", t =>
                        {
                            t.HasComment("Ligne de commande pour historique avec préservation des clés primaires");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("men_id")
                        .HasComment("Identifiant du menu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("men_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("men_date_debut")
                        .HasComment("Date de début de validité du menu");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("men_date_fin")
                        .HasComment("Date de fin de validité du menu");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("men_description")
                        .HasComment("Description du menu");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("men_disponible")
                        .HasComment("Indique si le menu est disponible");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("men_nom")
                        .HasComment("Nom du menu");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("men_prix")
                        .HasComment("Prix du menu");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("lie_id")
                        .HasComment("Restaurant proposant ce menu");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("menu", t =>
                        {
                            t.HasComment("Menu du restaurant");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.MenuPlat", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("men_id")
                        .HasComment("Menu contenant ce plat");

                    b.Property<int>("PlatId")
                        .HasColumnType("integer")
                        .HasColumnName("pla_id")
                        .HasComment("Plat du menu");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mpl_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("mpl_ordre")
                        .HasComment("Ordre d'affichage du plat dans le menu");

                    b.HasKey("MenuId", "PlatId");

                    b.HasIndex("PlatId");

                    b.HasIndex("MenuId", "Ordre")
                        .IsUnique();

                    b.ToTable("menu_plat", t =>
                        {
                            t.HasComment("Plat dans un menu");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("per_id")
                        .HasComment("Identifiant de la personne");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("per_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<string>("DepartementCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dep_code")
                        .HasComment("Département de résidence de la personne.");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("per_nom")
                        .HasComment("Nom de la personne");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("per_prenom")
                        .HasComment("Prénom de la personne");

                    b.HasKey("Id");

                    b.HasIndex("DepartementCode");

                    b.ToTable("personne", t =>
                        {
                            t.HasComment("Classe de base représentant une personne");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Plat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pla_id")
                        .HasComment("Identifiant du plat");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriePlatCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cat_code")
                        .HasComment("Catégorie du plat");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pla_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pla_description")
                        .HasComment("Description du plat");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("pla_disponible")
                        .HasComment("Indique si le plat est disponible");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pla_nom")
                        .HasComment("Nom du plat");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("pla_prix")
                        .HasComment("Prix du plat");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("lie_id")
                        .HasComment("Restaurant proposant ce plat");

                    b.HasKey("Id");

                    b.HasIndex("CategoriePlatCode");

                    b.HasIndex("RestaurantId");

                    b.ToTable("plat", t =>
                        {
                            t.HasComment("Plat du menu");
                        });

                    b.HasDiscriminator<string>("CategoriePlatCode").HasValue("AUTRE");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Prestataire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pst_id")
                        .HasComment("Identifiant de la personne");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pst_nom")
                        .HasComment("Nom de la personne");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pst_prenom")
                        .HasComment("Prénom de la personne");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pst_telephone")
                        .HasComment("Numéro de téléphone de l'employé.");

                    b.HasKey("Id");

                    b.HasIndex("Telephone");

                    b.HasIndex("Nom", "Prenom");

                    b.ToTable("prestataire", t =>
                        {
                            t.HasComment("Prestaire du restaurant");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Promotion", b =>
                {
                    b.Property<int>("PlatId")
                        .HasColumnType("integer")
                        .HasColumnName("pla_id")
                        .HasComment("Plat concerné par la promotion.");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("pro_active")
                        .HasComment("Indique si la promotion est active");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pro_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pro_date_debut")
                        .HasComment("Date de début de la promotion");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pro_date_fin")
                        .HasComment("Date de fin de la promotion");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pro_libelle")
                        .HasComment("Libellé de la promotion");

                    b.Property<int>("PourcentageReduction")
                        .HasColumnType("integer")
                        .HasColumnName("pro_pourcentage_reduction")
                        .HasComment("Pourcentage de réduction (0-100)");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("lie_id")
                        .HasComment("Restaurant concerné par la promotion (null si globale)");

                    b.HasKey("PlatId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("promotion", t =>
                        {
                            t.HasComment("Promotion sur un plat");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rev_id")
                        .HasComment("Identifiant de la réservation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("per_id")
                        .HasComment("Client ayant fait la réservation");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rev_commentaire")
                        .HasComment("Commentaire sur la réservation");

                    b.Property<bool>("Confirmee")
                        .HasColumnType("boolean")
                        .HasColumnName("rev_confirmee")
                        .HasComment("Indique si la réservation est confirmée");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rev_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rev_date_reservation")
                        .HasComment("Date et heure de la réservation");

                    b.Property<int>("NombrePersonnes")
                        .HasColumnType("integer")
                        .HasColumnName("rev_nombre_personnes")
                        .HasComment("Nombre de personnes");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("lie_id")
                        .HasComment("Restaurant concerné par la réservation");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer")
                        .HasColumnName("tab_id")
                        .HasComment("Table réservée");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("TableId", "DateReservation")
                        .IsUnique();

                    b.ToTable("reservation", t =>
                        {
                            t.HasComment("Réservation d'une table");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.TableRestaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tab_id")
                        .HasComment("Identifiant de la table");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacite")
                        .HasColumnType("integer")
                        .HasColumnName("tab_capacite")
                        .HasComment("Capacité de la table (nombre de places)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tab_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("tab_disponible")
                        .HasComment("Indique si la table est disponible");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tab_numero")
                        .HasComment("Numéro de la table");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("lie_id")
                        .HasComment("Restaurant auquel appartient la table");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "Numero")
                        .IsUnique();

                    b.ToTable("table_restaurant", t =>
                        {
                            t.HasComment("Table du restaurant");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Vaisselle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vsl_id")
                        .HasDefaultValueSql("nextval('seq_vaisselle')")
                        .HasComment("Id de la vaisselle");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"), "seq_vaisselle");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vsl_description")
                        .HasComment("Description de la vaisselle.");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("TopModel.Sample.Restaurant.Models.CategoriePlat", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cat_code")
                        .HasComment("Code de la catégorie");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_libelle")
                        .HasComment("Libellé de la catégorie");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("cat_ordre")
                        .HasComment("Ordre d'affichage dans le menu.");

                    b.Property<decimal?>("PrixMoyen")
                        .HasColumnType("numeric")
                        .HasColumnName("cat_prix_moyen")
                        .HasComment("Prix moyen de la catégorie, à titre indicatif.");

                    b.HasKey("Code");

                    b.HasIndex("Libelle");

                    b.HasIndex("Ordre")
                        .IsUnique();

                    b.ToTable("categorie_plat", t =>
                        {
                            t.HasComment("Catégorie de plat");
                        });

                    b.HasData(
                        new
                        {
                            Code = "BOISSON",
                            Libelle = "restaurant.categoriePlat.values.Boisson",
                            Ordre = 1,
                            PrixMoyen = 2m
                        },
                        new
                        {
                            Code = "ENTREE",
                            Libelle = "restaurant.categoriePlat.values.Entree",
                            Ordre = 2
                        },
                        new
                        {
                            Code = "PRINCIPAL",
                            Libelle = "restaurant.categoriePlat.values.Principal",
                            Ordre = 3,
                            PrixMoyen = 10m
                        },
                        new
                        {
                            Code = "DESSERT",
                            Libelle = "restaurant.categoriePlat.values.Dessert",
                            Ordre = 4
                        },
                        new
                        {
                            Code = "AUTRE",
                            Libelle = "restaurant.categoriePlat.values.Autre",
                            Ordre = 5
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Restaurant.Models.Departement", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dep_code")
                        .HasComment("Code du département.");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dep_libelle")
                        .HasComment("Libellé du département.");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reg_code")
                        .HasComment("Région associée.");

                    b.HasKey("Code");

                    b.HasIndex("Libelle");

                    b.HasIndex("RegionCode");

                    b.ToTable("departement", t =>
                        {
                            t.HasComment("Département");
                        });

                    b.HasData(
                        new
                        {
                            Code = "92",
                            Libelle = "restaurant.departement.values.HautsDeSeine",
                            RegionCode = "IDF"
                        },
                        new
                        {
                            Code = "75",
                            Libelle = "restaurant.departement.values.Paris",
                            RegionCode = "IDF"
                        },
                        new
                        {
                            Code = "94",
                            Libelle = "restaurant.departement.values.SeineEtMarne",
                            RegionCode = "IDF"
                        },
                        new
                        {
                            Code = "93",
                            Libelle = "restaurant.departement.values.SeineSaintDenis",
                            RegionCode = "IDF"
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Restaurant.Models.Region", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reg_code")
                        .HasComment("Code de la région.");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reg_libelle")
                        .HasComment("Libellé de la région.");

                    b.Property<string>("NomResponsable")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reg_nom_responsable")
                        .HasComment("Nom du responsable de la région.");

                    b.HasKey("Code");

                    b.HasIndex("Libelle");

                    b.ToTable("region", t =>
                        {
                            t.HasComment("Région");
                        });

                    b.HasData(
                        new
                        {
                            Code = "IDF",
                            Libelle = "restaurant.region.values.Idf"
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Fournisseur", b =>
                {
                    b.HasBaseType("TopModel.Sample.Clients.Db.Models.Restaurant.Lieu");

                    b.Property<bool?>("Bio")
                        .HasColumnType("boolean")
                        .HasColumnName("frn_bio")
                        .HasComment("Si le fournisseur fait du bio.");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frn_telephone")
                        .HasComment("Numéro de téléphone");

                    b.ToTable("lieu");

                    b.HasDiscriminator().HasValue("fournisseur");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Restaurant", b =>
                {
                    b.HasBaseType("TopModel.Sample.Clients.Db.Models.Restaurant.Lieu");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("res_date_creation")
                        .HasComment("Date de création de l'enregistrement");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("res_telephone")
                        .HasComment("Numéro de téléphone");

                    b.ToTable("lieu");

                    b.HasDiscriminator().HasValue("restaurant");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Client", b =>
                {
                    b.HasBaseType("TopModel.Sample.Clients.Db.Models.Restaurant.Personne");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cli_email")
                        .HasComment("Adresse email du client");

                    b.ToTable("client", t =>
                        {
                            t.HasComment("Client du restaurant");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Employe", b =>
                {
                    b.HasBaseType("TopModel.Sample.Clients.Db.Models.Restaurant.Personne");

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emp_date_embauche")
                        .HasComment("Date d'embauche");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emp_date_naissance")
                        .HasComment("Date de naissance");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("emp_matricule")
                        .HasComment("Matricule de l'employé");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("lie_id")
                        .HasComment("Restaurant où travaille l'employé");

                    b.Property<decimal?>("Salaire")
                        .HasColumnType("numeric")
                        .HasColumnName("emp_salaire")
                        .HasComment("Salaire de l'employé");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("emp_telephone")
                        .HasComment("Numéro de téléphone de l'employé.");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.HasIndex("RestaurantId");

                    b.HasIndex("Telephone");

                    b.ToTable("employe", t =>
                        {
                            t.HasComment("Employé du restaurant");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.PlatBoisson", b =>
                {
                    b.HasBaseType("TopModel.Sample.Clients.Db.Models.Restaurant.Plat");

                    b.Property<int>("Volume")
                        .HasColumnType("integer")
                        .HasColumnName("volume")
                        .HasComment("Volume de la boisson");

                    b.ToTable("plat");

                    b.HasDiscriminator().HasValue("BOISSON");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.PlatDessert", b =>
                {
                    b.HasBaseType("TopModel.Sample.Clients.Db.Models.Restaurant.Plat");

                    b.ToTable("plat");

                    b.HasDiscriminator().HasValue("DESSERT");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.PlatEntree", b =>
                {
                    b.HasBaseType("TopModel.Sample.Clients.Db.Models.Restaurant.Plat");

                    b.ToTable("plat");

                    b.HasDiscriminator().HasValue("ENTREE");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.PlatPrincipal", b =>
                {
                    b.HasBaseType("TopModel.Sample.Clients.Db.Models.Restaurant.Plat");

                    b.Property<bool>("Vegetarien")
                        .HasColumnType("boolean")
                        .HasColumnName("vegetarien")
                        .HasComment("Si le plat est végétarien.");

                    b.ToTable("plat");

                    b.HasDiscriminator().HasValue("PRINCIPAL");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Assiette", b =>
                {
                    b.HasBaseType("TopModel.Sample.Clients.Db.Models.Restaurant.Vaisselle");

                    b.Property<int>("Taille")
                        .HasColumnType("integer")
                        .HasColumnName("ast_taille")
                        .HasComment("Taille de l'assiette.");

                    b.ToTable("assiette", t =>
                        {
                            t.HasComment("Assiette.");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Couvert", b =>
                {
                    b.HasBaseType("TopModel.Sample.Clients.Db.Models.Restaurant.Vaisselle");

                    b.ToTable("couvert", t =>
                        {
                            t.HasComment("Couvert.");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Verre", b =>
                {
                    b.HasBaseType("TopModel.Sample.Clients.Db.Models.Restaurant.Vaisselle");

                    b.Property<bool>("APied")
                        .HasColumnType("boolean")
                        .HasColumnName("vrr_a_pied")
                        .HasComment("Si le verre est à pied ou non.");

                    b.ToTable("verre", t =>
                        {
                            t.HasComment("Verre.");
                        });
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.AvisClient", b =>
                {
                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Client", "Client")
                        .WithMany("AvisClients")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Restaurant", "Restaurant")
                        .WithMany("AvisClients")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.CategoriePlatRegion", b =>
                {
                    b.HasOne("TopModel.Sample.Restaurant.Models.CategoriePlat", "CategoriePlat")
                        .WithMany()
                        .HasForeignKey("CategoriePlatCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TopModel.Sample.Restaurant.Models.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriePlat");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Commande", b =>
                {
                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.AvisClient", "AvisClient")
                        .WithOne()
                        .HasForeignKey("TopModel.Sample.Clients.Db.Models.Restaurant.Commande", "AvisClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.TableRestaurant", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AvisClient");

                    b.Navigation("Client");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.LigneCommande", b =>
                {
                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Commande", "Commande")
                        .WithMany("Lignes")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Plat", "Plat")
                        .WithMany()
                        .HasForeignKey("PlatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Plat");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.LigneCommandeHistorique", b =>
                {
                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.CommandeHistorique", null)
                        .WithMany()
                        .HasForeignKey("CommandeHistoriqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Menu", b =>
                {
                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Restaurant", "Restaurant")
                        .WithMany("Menus")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.MenuPlat", b =>
                {
                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Menu", "Menu")
                        .WithMany("Plats")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Plat", "Plat")
                        .WithMany()
                        .HasForeignKey("PlatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Plat");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Personne", b =>
                {
                    b.HasOne("TopModel.Sample.Restaurant.Models.Departement", null)
                        .WithMany()
                        .HasForeignKey("DepartementCode")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Plat", b =>
                {
                    b.HasOne("TopModel.Sample.Restaurant.Models.CategoriePlat", "CategoriePlat")
                        .WithMany()
                        .HasForeignKey("CategoriePlatCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Restaurant", "Restaurant")
                        .WithMany("Plats")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriePlat");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Promotion", b =>
                {
                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Plat", "Plat")
                        .WithOne("Promotion")
                        .HasForeignKey("TopModel.Sample.Clients.Db.Models.Restaurant.Promotion", "PlatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Restaurant", "Restaurant")
                        .WithMany("Promotions")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Plat");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Reservation", b =>
                {
                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.TableRestaurant", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.TableRestaurant", b =>
                {
                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TopModel.Sample.Restaurant.Models.Departement", b =>
                {
                    b.HasOne("TopModel.Sample.Restaurant.Models.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Client", b =>
                {
                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Personne", null)
                        .WithOne()
                        .HasForeignKey("TopModel.Sample.Clients.Db.Models.Restaurant.Client", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Employe", b =>
                {
                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Personne", null)
                        .WithOne()
                        .HasForeignKey("TopModel.Sample.Clients.Db.Models.Restaurant.Employe", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TopModel.Sample.Clients.Db.Models.Restaurant.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Commande", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Menu", b =>
                {
                    b.Navigation("Plats");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Plat", b =>
                {
                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Restaurant", b =>
                {
                    b.Navigation("AvisClients");

                    b.Navigation("Menus");

                    b.Navigation("Plats");

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("TopModel.Sample.Clients.Db.Models.Restaurant.Client", b =>
                {
                    b.Navigation("AvisClients");
                });
#pragma warning restore 612, 618
        }
    }
}
