----
---- ATTENTION CE FICHIER EST GENERE AUTOMATIQUEMENT !
----

-- =========================================================================================== 
--   Application Name	:	Exemple 
--   Script Name		:	crebas.sql
--   Description		:	Script de création des tables.
-- =========================================================================================== 
/**
  * Création de la table PROFIL
 **/
create table PROFIL (
	PRO_ID int8 generated by default as identity not null,
	CODE varchar(3),
	constraint PK_PROFIL primary key (PRO_ID)
)
;

/**
  * Création de la table TYPE_PROFIL
 **/
create table TYPE_PROFIL (
	CODE varchar(3) not null,
	LIBELLE varchar(3) not null,
	constraint PK_TYPE_PROFIL primary key (CODE)
)
;

/**
  * Création de la table TYPE_UTILISATEUR
 **/
create table TYPE_UTILISATEUR (
	TUT_CODE varchar(3) not null,
	TUT_LIBELLE varchar(3) not null,
	constraint PK_TYPE_UTILISATEUR primary key (TUT_CODE)
)
;

/**
  * Création de la table UTILISATEUR
 **/
create table UTILISATEUR (
	UTI_DATE_CREATION date,
	UTI_DATE_MODIFICATION date,
	UTI_ID int8 generated by default as identity not null,
	UTI_AGE numeric(20, 9),
	PRO_ID int8,
	UTI_EMAIL varchar(50),
	TUT_CODE varchar(3),
	constraint PK_UTILISATEUR primary key (UTI_ID)
)
;

