<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>4.2.2</Version>
    <Description>Utilitaires TopModel.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Meziantou.Framework.Globbing" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
</Project>
