<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>4.0.0-rc.1</Version>
    <Description>Utilitaires TopModel.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Meziantou.Framework.Globbing" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="NuGet.Commands" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
</Project>
