----
---- ATTENTION CE FICHIER EST GENERE AUTOMATIQUEMENT !
----

-- ===========================================================================================
--   Application Name	:	Restaurant 
--   Script Name		:	01_tables.sql
--   Description		:	Script de création des tables.
-- ===========================================================================================

/**
  * Création de la table assiette
 **/
create table assiette (
	vsl_id int,
	vsl_description varchar(100) not null,
	ast_taille int not null,
	constraint pk_assiette primary key (vsl_id)
);

/**
  * Création de la séquence pour la clé primaire de la table vaisselle
 **/
create sequence SEQ_VAISSELLE as int start with 1000 increment by 50;

/**
  * Création de la table avis_client
 **/
create table avis_client (
	avi_id int generated by default as identity,
	avi_note int not null,
	avi_commentaire varchar(100),
	avi_date_avis timestamp not null,
	avi_approuve boolean not null,
	per_id int not null,
	lie_id int not null,
	avi_date_creation timestamp not null,
	constraint pk_avis_client primary key (avi_id)
);

/**
  * Création de la table categorie_plat
 **/
create table categorie_plat (
	cat_code varchar(10),
	cat_libelle varchar(100) not null,
	cat_ordre int not null,
	cat_prix_moyen decimal,
	constraint pk_categorie_plat primary key (cat_code)
);

/**
  * Création de la table categorie_plat_region
 **/
create table categorie_plat_region (
	reg_code varchar(10),
	cat_code varchar(10),
	constraint pk_categorie_plat_region primary key (reg_code,cat_code)
);

/**
  * Création de la table client
 **/
create table client (
	cli_email varchar(100),
	per_id int,
	constraint pk_client primary key (per_id)
);

/**
  * Création de la table statut_commande
 **/
create type statut_commande as enum ('EN_ATT', 'EN_PREP', 'PRETE', 'SERVIE', 'ANNULE'); 

/**
  * Création de la table commande
 **/
create table commande (
	com_id int generated by default as identity(start with 2 increment by 2),
	com_date_commande timestamp not null,
	com_date_livraison timestamp,
	com_montant_total decimal not null,
	per_id int not null,
	tab_id int,
	rev_id int,
	stc_code statut_commande not null,
	avi_id int,
	com_date_creation timestamp not null,
	constraint pk_commande primary key (com_id)
);

/**
  * Création de la table commande_historique
 **/
create table commande_historique (
	com_id int,
	com_date_commande timestamp not null,
	com_date_livraison timestamp,
	com_montant_total decimal not null,
	per_id int not null,
	tab_id int,
	rev_id int,
	stc_code statut_commande not null,
	avi_id int,
	com_date_creation timestamp not null,
	constraint pk_commande_historique primary key (com_id)
);

/**
  * Création de la table couvert
 **/
create table couvert (
	vsl_id int,
	vsl_description varchar(100) not null,
	constraint pk_couvert primary key (vsl_id)
);

/**
  * Création de la table departement
 **/
create table departement (
	dep_code varchar(10),
	dep_libelle varchar(100) not null,
	reg_code varchar(10) not null,
	constraint pk_departement primary key (dep_code)
);

/**
  * Création de la table employe
 **/
create table employe (
	emp_telephone varchar(20),
	emp_date_naissance timestamp,
	emp_matricule varchar(10) not null,
	emp_date_embauche timestamp not null,
	emp_salaire decimal,
	lie_id int not null,
	per_id int,
	constraint pk_employe primary key (per_id)
);

/**
  * Création de la table lieu
 **/
create table lieu (
	lie_id int generated by default as identity,
	lie_nom varchar(100) not null,
	lie_adresse varchar(100),
	lie_discriminator varchar(128) not null,
	res_telephone varchar(20),
	res_date_creation timestamp,
	frn_telephone varchar(20),
	frn_bio boolean,
	constraint pk_lieu primary key (lie_id)
);

/**
  * Création de la table ligne_commande
 **/
create table ligne_commande (
	lig_id int generated by default as identity(start with 2 increment by 2),
	lig_quantite int not null,
	lig_prix_unitaire decimal not null,
	lig_prix_total decimal not null,
	com_id int not null,
	pla_id int not null,
	lig_date_creation timestamp not null,
	constraint pk_ligne_commande primary key (lig_id)
);

/**
  * Création de la table ligne_commande_historique
 **/
create table ligne_commande_historique (
	lig_id int,
	lig_quantite int not null,
	lig_prix_unitaire decimal not null,
	lig_prix_total decimal not null,
	pla_id int not null,
	lig_date_creation timestamp not null,
	com_id int not null,
	constraint pk_ligne_commande_historique primary key (lig_id)
);

/**
  * Création de la table menu
 **/
create table menu (
	men_id int,
	men_nom varchar(100) not null,
	men_description varchar(100),
	men_prix decimal not null,
	men_disponible boolean not null,
	men_date_debut timestamp,
	men_date_fin timestamp,
	lie_id int not null,
	men_date_creation timestamp not null,
	constraint pk_menu primary key (men_id)
);

/**
  * Création de la séquence pour la clé primaire de la table menu
 **/
create sequence SEQ_MENU as int start with 1000 increment by 50 owned by menu.men_id;

/**
  * Création de la table menu_plat
 **/
create table menu_plat (
	men_id int,
	pla_id int,
	mpl_ordre int not null,
	mpl_date_creation timestamp not null,
	constraint pk_menu_plat primary key (men_id,pla_id)
);

/**
  * Création de la table personne
 **/
create table personne (
	per_id int generated by default as identity,
	per_nom varchar(100) not null,
	per_prenom varchar(100) not null,
	dep_code varchar(10),
	per_date_creation timestamp not null,
	constraint pk_personne primary key (per_id)
);

/**
  * Création de la table plat
 **/
create table plat (
	pla_id int,
	pla_nom varchar(100) not null,
	pla_description varchar(100),
	pla_prix decimal not null,
	pla_disponible boolean not null,
	cat_code varchar(10) not null,
	lie_id int not null,
	pla_date_creation timestamp not null,
	pbo_volume int,
	ppr_vegetarien boolean,
	constraint pk_plat primary key (pla_id)
);

/**
  * Création de la séquence pour la clé primaire de la table plat
 **/
create sequence SEQ_PLAT as int start with 1000 increment by 50 owned by plat.pla_id;

/**
  * Création de la table prestataire
 **/
create table prestataire (
	pst_id int generated by default as identity,
	pst_nom varchar(100) not null,
	pst_prenom varchar(100) not null,
	pst_telephone varchar(20),
	constraint pk_prestataire primary key (pst_id)
);

/**
  * Création de la table promotion
 **/
create table promotion (
	pla_id int,
	pro_libelle varchar(100) not null,
	pro_pourcentage_reduction int not null,
	pro_date_debut timestamp not null,
	pro_date_fin timestamp not null,
	pro_active boolean not null,
	lie_id int,
	pro_date_creation timestamp not null,
	constraint pk_promotion primary key (pla_id)
);

/**
  * Création de la séquence pour la clé primaire de la table promotion
 **/
create sequence SEQ_PROMOTION as int start with 1000 increment by 50 owned by promotion.pla_id;

/**
  * Création de la table region
 **/
create table region (
	reg_code varchar(10),
	reg_libelle varchar(100) not null,
	reg_nom_responsable varchar(100),
	constraint pk_region primary key (reg_code)
);

/**
  * Création de la table reservation
 **/
create table reservation (
	rev_id int,
	rev_date_reservation timestamp not null,
	rev_nombre_personnes int not null,
	rev_commentaire varchar(100),
	rev_confirmee boolean not null,
	per_id int not null,
	tab_id int,
	lie_id int not null,
	rev_date_creation timestamp not null,
	constraint pk_reservation primary key (rev_id)
);

/**
  * Création de la séquence pour la clé primaire de la table reservation
 **/
create sequence SEQ_RESERVATION as int start with 1000 increment by 50 owned by reservation.rev_id;

/**
  * Création de la table table
 **/
create table "table" (
	tab_id int generated by default as identity,
	tab_numero varchar(10) not null,
	tab_capacite int not null,
	tab_disponible boolean not null,
	lie_id int not null,
	tab_date_creation timestamp not null,
	constraint pk_table primary key (tab_id)
);

/**
  * Création de la table translation
 **/
create table translation (
	tra_resource_key varchar(100),
	tra_value varchar(100) not null,
	tra_lang varchar(100),
	constraint pk_translation primary key (tra_resource_key,tra_lang)
);

/**
  * Création de la table type_terrasse
 **/
create type type_terrasse as enum ('INT', 'EXT'); 

/**
  * Création de la table verre
 **/
create table verre (
	vsl_id int,
	vsl_description varchar(100) not null,
	vrr_a_pied boolean not null,
	constraint pk_verre primary key (vsl_id)
);
