using Microsoft.Extensions.Logging;

namespace TopModel.Generator.Sql.Procedural;

/// <summary>
/// Générateur de PL-SQL.
/// </summary>
public class PostgreSchemaGenerator : AbstractSchemaGenerator
{
    private SqlConfig _config;

    public PostgreSchemaGenerator(SqlConfig config, ILogger<ProceduralSqlGenerator> logger)
        : base(config, logger)
    {
        _config = config;
    }

    protected override string BatchSeparator => ";";

    protected override bool SupportsClusteredKey => false;

    protected override bool UseQuotes => false;

    /// <summary>
    /// Gère l'auto-incrémentation des clés primaires en ajoutant identity à la colonne.
    /// </summary>
    /// <param name="writerCrebas">Flux d'écriture création bases.</param>
    protected override void WriteIdentityColumn(SqlFileWriter writerCrebas)
    {
        writerCrebas.Write(" generated by default as identity");
        if (Config.Identity.Increment != null || Config.Identity.Start != null)
        {
            writerCrebas.Write(" (");
            if (Config.Identity.Start != null)
            {
                writerCrebas.Write($"{$"start with {Config.Identity.Start}"}");
            }

            if (Config.Identity.Increment != null)
            {
                writerCrebas.Write($"{$" increment {Config.Identity.Increment}"}");
            }

            writerCrebas.Write(")");
        }
    }
}