using Microsoft.Extensions.Logging;
using TopModel.Core.Model;
using TopModel.Utils;

namespace TopModel.Generator.Sql.Procedural.Postgres;

public class PostgresTablesGenerator(ILogger<PostgresTablesGenerator> logger, IFileWriterProvider writerProvider)
    : AbstractSqlTablesGenerator(logger, writerProvider)
{
    protected override string JsonType => "jsonb";

    protected override bool SupportsClusteredKey => false;

    /// <summary>
    /// Gère l'auto-incrémentation des clés primaires en ajoutant identity à la colonne.
    /// </summary>
    /// <param name="writer">Flux d'écriture création bases.</param>
    protected override void WriteIdentityColumn(IFileWriter writer, GeneratedValueDefinition generatedValue)
    {
        writer.Write(" generated by default as identity");
        if (generatedValue.Start != 1 || generatedValue.Increment != 1)
        {
            writer.Write(" (");
            if (generatedValue.Start != 1)
            {
                writer.Write($"start with {generatedValue.Start}");
            }

            if (generatedValue.Increment != 1)
            {
                writer.Write($"{(generatedValue.Start != 1 ? " " : string.Empty)}increment {generatedValue.Increment}");
            }

            writer.Write(")");
        }
    }
}
