using Microsoft.Extensions.Logging;
using TopModel.Core.Model;
using TopModel.Utils;

namespace TopModel.Generator.Sql.Procedural.Postgres;

public class PostgresCrebasGenerator(ILogger<PostgresCrebasGenerator> logger, IFileWriterProvider writerProvider)
    : AbstractCrebasGenerator(logger, writerProvider)
{
    public override string Name => "PostgresCrebasGen";

    protected override string JsonType => "jsonb";

    protected override bool SupportsClusteredKey => false;

    /// <summary>
    /// Gère l'auto-incrémentation des clés primaires en ajoutant identity à la colonne.
    /// </summary>
    /// <param name="writer">Flux d'écriture création bases.</param>
    protected override void WriteIdentityColumn(IFileWriter writer)
    {
        writer.Write(" generated by default as identity");
        if (Config.Procedural!.Identity.Increment != null || Config.Procedural!.Identity.Start != null)
        {
            writer.Write(" (");
            if (Config.Procedural!.Identity.Start != null)
            {
                writer.Write($"{$"start with {Config.Procedural!.Identity.Start}"}");
            }

            if (Config.Procedural!.Identity.Increment != null)
            {
                writer.Write($"{$" increment {Config.Procedural!.Identity.Increment}"}");
            }

            writer.Write(")");
        }
    }

    protected override void WriteSequenceDeclaration(Class classe, IFileWriter writer, string tableName)
    {
        writer.Write(
            $"create sequence {Config.GetSequenceName(classe)} as {Config.GetType(classe.PrimaryKey.Single(), forceAssociationPropertyType: true).ToUpper()}"
        );

        if (Config.Procedural!.Identity.Start != null)
        {
            writer.Write($"{$" start {Config.Procedural!.Identity.Start}"}");
        }

        if (Config.Procedural!.Identity.Increment != null)
        {
            writer.Write($"{$" increment {Config.Procedural!.Identity.Increment}"}");
        }

        writer.Write($" owned by {tableName}.{classe.PrimaryKey.Single().SqlName}");
    }
}
