using Microsoft.Extensions.Logging;
using TopModel.Core.Model;
using TopModel.Utils;

namespace TopModel.Generator.Sql.Procedural.Postgres;

public class PostgresTablesGenerator(ILogger<PostgresTablesGenerator> logger, IFileWriterProvider writerProvider)
    : AbstractSqlTablesGenerator(logger, writerProvider)
{
    protected override string JsonType => "jsonb";

    protected override bool SupportsClusteredKey => false;

    /// <summary>
    /// Gère l'auto-incrémentation des clés primaires en ajoutant identity à la colonne.
    /// </summary>
    /// <param name="writer">Flux d'écriture création bases.</param>
    protected override void WriteIdentityColumn(IFileWriter writer)
    {
        writer.Write(" generated by default as identity");
        if (Config.Procedural!.Identity.Increment != null || Config.Procedural!.Identity.Start != null)
        {
            writer.Write(" (");
            if (Config.Procedural!.Identity.Start != null)
            {
                writer.Write($"{$"start with {Config.Procedural!.Identity.Start}"}");
            }

            if (Config.Procedural!.Identity.Increment != null)
            {
                writer.Write($"{$" increment {Config.Procedural!.Identity.Increment}"}");
            }

            writer.Write(")");
        }
    }

    protected override void WriteSequenceDeclaration(Class classe, IFileWriter writer)
    {
        writer.Write(
            $"create sequence {Config.GetSequenceName(classe)} as {Config.GetType(classe.PrimaryKey.Single()).ToUpper()} start {Config.Procedural?.Identity.Start ?? 1} increment {Config.Procedural?.Identity.Increment ?? 1}"
        );

        if (classe.HasTable)
        {
            writer.Write($" owned by {classe.SqlName}.{classe.PrimaryKey.Single().SqlName}");
        }
    }
}
