using System.Text;
using Microsoft.Extensions.Logging;
using TopModel.Core.Model;
using TopModel.Generator.Core;
using TopModel.Utils;

namespace TopModel.Generator.Sql.Ssdt;

/// <summary>
/// Scripter permettant d'écrire les scripts de création d'une table SQL avec :
/// - sa structure
/// - sa contrainte PK
/// - ses contraintes FK
/// - ses indexes FK
/// - ses contraintes d'unicité sur colonne unique.
/// </summary>
public class SsdtTableGenerator(ILogger<SsdtTableGenerator> logger, IFileWriterProvider writerProvider)
    : ClassGeneratorBase<SqlConfig>(logger, writerProvider)
{
    public override string Name => "SsdtTableGen";

    protected override bool FilterClass(Class classe)
    {
        return classe.IsPersistent && !classe.Abstract;
    }

    protected override string GetFileName(Class classe, string tag)
    {
        return Path.Combine(Config.Ssdt!.TableScriptFolder!, classe.SqlName + ".sql");
    }

    protected override void HandleClass(string fileName, Class classe, string tag)
    {
        using var writer = this.OpenSqlWriter(fileName);

        var useCompression = false;

        // Entête du fichier.
        WriteHeader(writer, classe.SqlName);

        // Ouverture du create table.
        WriteCreateTableOpening(writer, classe);

        // Intérieur du create table.
        WriteInsideInstructions(writer, classe);

        // Fin du create table.
        WriteCreateTableClosing(writer, classe, useCompression);

        // Indexes sur les clés étrangères.
        WriteIndexes(writer, classe, classe.AllProperties);

        // Définition
        if (Config.Ssdt!.GenerateComments)
        {
            WriteComments(writer, classe);
        }
    }

    /// <summary>
    /// Ecrit le SQL pour une colonne.
    /// </summary>
    /// <param name="sb">Flux.</param>
    /// <param name="property">Propriété.</param>
    protected virtual void WriteColumn(StringBuilder sb, IProperty property)
    {
        var persistentType =
            property is { Composition: null } ? Config.GetType(property)
            : Config.TargetDBMS == TargetDBMS.Postgre ? "jsonb"
            : "json";

        if (Config.TargetDBMS == TargetDBMS.Sqlserver)
        {
            sb.Append('[');
        }

        sb.Append(property.SqlName);

        if (Config.TargetDBMS == TargetDBMS.Sqlserver)
        {
            sb.Append(']');
        }

        sb.Append($" {persistentType}");

        if (
            property.Association == null
            && property.PrimaryKey
            && property.AutoGeneratedValue
            && Config.GetType(property).Contains("int")
            && !Config.Ssdt!.DisableIdentity
        )
        {
            if (Config.TargetDBMS == TargetDBMS.Sqlserver)
            {
                sb.Append(" identity");
            }
            else
            {
                sb.Append(" not null generated always as identity");
            }
        }

        if (property.Required && !property.PrimaryKey)
        {
            sb.Append(" not null");
        }

        var defaultValue = Config.GetValue(property);
        if (defaultValue != "null")
        {
            sb.Append($" default {defaultValue}");
        }
    }

    /// <summary>
    /// Ecrit la création de la propriété de description de la table.
    /// </summary>
    /// <param name="writer">Writer.</param>
    /// <param name="classe">Classe de la table.</param>
    protected virtual void WriteComments(IFileWriter writer, Class classe)
    {
        writer.WriteComments(classe, Config);
    }

    /// <summary>
    /// Ecrit le pied du script.
    /// </summary>
    /// <param name="writer">Flux.</param>
    /// <param name="classe">Classe de la table.</param>
    /// <param name="useCompression">Indique si on utilise la compression.</param>
    protected virtual void WriteCreateTableClosing(IFileWriter writer, Class classe, bool useCompression)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(classe);

        writer.WriteLine(")");

        if (useCompression)
        {
            writer.WriteLine("WITH (DATA_COMPRESSION=PAGE)");
        }

        writer.WriteLine(Config.TargetDBMS == TargetDBMS.Sqlserver ? "go" : ";");
        writer.WriteLine();
    }

    /// <summary>
    /// Ecrit l'ouverture du create table.
    /// </summary>
    /// <param name="writer">Flux.</param>
    /// <param name="table">Table.</param>
    protected virtual void WriteCreateTableOpening(IFileWriter writer, Class table)
    {
        if (Config.TargetDBMS == TargetDBMS.Sqlserver)
        {
            writer.WriteLine($"create table [dbo].[{table.SqlName}] (");
        }
        else
        {
            writer.WriteLine($"create table {table.SqlName} (");
        }
    }

    /// <summary>
    /// Génère la contrainte de clef étrangère.
    /// </summary>
    /// <param name="sb">Flux d'écriture.</param>
    /// <param name="property">Propriété portant la clef étrangère.</param>
    protected virtual void WriteForeignKeyConstraint(StringBuilder sb, IProperty property)
    {
        var referenceClass = property.Association!;

        if (Config.TargetDBMS == TargetDBMS.Sqlserver)
        {
            var propertyConcat = "[" + property.SqlName + "]";
            sb.Append("constraint [")
                .Append(property.ForeignKeyName)
                .Append("] foreign key (")
                .Append(propertyConcat)
                .Append(") ");
            sb.Append("references [dbo].[").Append(referenceClass.SqlName).Append("] (");
            sb.Append('[').Append(property.AssociationProperty!.SqlName).Append(']');
            sb.Append(')');
        }
        else
        {
            sb.Append(
                $"constraint FK_{property.ForeignKeyName} foreign key ({property.SqlName}) references {referenceClass.SqlName} ({property.AssociationProperty!.SqlName})"
            );
        }
    }

    /// <summary>
    /// Ecrit l'entête du fichier.
    /// </summary>
    /// <param name="writer">Flux.</param>
    /// <param name="tableName">Nom de la table.</param>
    protected virtual void WriteHeader(IFileWriter writer, string tableName)
    {
        writer.WriteSqlFileHeader(description: $"Création de la table {tableName}.");
        writer.WriteLine();
    }

    protected virtual void WriteIndex(
        IFileWriter writer,
        string indexName,
        string tableName,
        params IEnumerable<string> propertyNames
    )
    {
        if (Config.TargetDBMS == TargetDBMS.Sqlserver)
        {
            writer.WriteLine($"create nonclustered index [{indexName}]");
            writer.Write("\ton [dbo].[" + tableName + "] (");
            writer.Write(string.Join(", ", propertyNames.Select(n => $"[{n}] ASC")));
            writer.Write(")");
            writer.WriteLine();
            writer.WriteLine("go");
        }
        else
        {
            writer.WriteLine($"create index {indexName}");
            writer.Write($"\ton {tableName} (");
            writer.Write(string.Join(", ", propertyNames.Select(n => $"{n} asc")));
            writer.WriteLine(");");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// Génère les indexes portant sur les FK.
    /// </summary>
    /// <param name="writer">Flux d'écriture.</param>
    /// <param name="tableName">Nom de la table.</param>
    /// <param name="properties">Champs.</param>
    protected virtual void WriteIndexes(IFileWriter writer, Class classe, IEnumerable<IProperty> properties)
    {
        foreach (
            var property in properties.Where(p =>
                p.Association != null && (p.Class.PrimaryKey.Count() != 1 || p.Class.PrimaryKey.Single() != p)
            )
        )
        {
            writer.WriteLine($"/* Index on foreign key column for {classe.SqlName}.{property.SqlName} */");
            WriteIndex(writer, property.IndexForeignKeyName!, classe.SqlName, property.SqlName);
        }

        foreach (var index in classe.Indexes.Where(idx => !idx.Unique))
        {
            writer.WriteLine($"/* Index {index.SqlName} on {classe.SqlName} */");
            WriteIndex(writer, index.SqlName, classe.SqlName, index.Properties.Select(p => p.SqlName));
        }
    }

    /// <summary>
    /// Ecrit les instructions à l'intérieur du create table.
    /// </summary>
    /// <param name="writer">Flux.</param>
    /// <param name="table">Table.</param>
    protected virtual void WriteInsideInstructions(IFileWriter writer, Class table)
    {
        // Construction d'une liste de toutes les instructions.
        var definitions = new List<string>();
        var sb = new StringBuilder();

        foreach (var property in table.AllProperties)
        {
            sb.Clear();
            WriteColumn(sb, property);
            definitions.Add(sb.ToString());
        }

        // Primary Key
        sb.Clear();
        WritePkLine(sb, table, table.AllProperties);

        definitions.Add(sb.ToString());

        // Foreign key constraints
        foreach (
            var property in table.AllProperties.Where(ap =>
                (ap.Association?.IsPersistent ?? false) && Config.AvailableClasses.Contains(ap.Association)
            )
        )
        {
            sb.Clear();
            WriteForeignKeyConstraint(sb, property);
            definitions.Add(sb.ToString());
        }

        // Unique constraints (clés unique déclarées via "unique:" et index uniques via "indexes:")
        definitions.AddRange(WriteUniqueKeyConstraints(table));

        // Ecriture de la liste concaténée.
        var separator = "," + Environment.NewLine;
        writer.Write(string.Join(separator, definitions.Select(x => "\t" + x)));
    }

    /// <summary>
    /// Ecrit la ligne de création de la PK.
    /// </summary>
    /// <param name="sb">Flux.</param>
    /// <param name="classe">Classe.</param>
    protected virtual void WritePkLine(StringBuilder sb, Class classe, IEnumerable<IProperty> properties)
    {
        var pkCount = 0;

        if (!properties.Any(p => p.PrimaryKey))
        {
            return;
        }

        if (Config.TargetDBMS == TargetDBMS.Sqlserver)
        {
            sb.Append("constraint [PK_").Append(classe.SqlName).Append("] primary key clustered (");
        }
        else
        {
            sb.Append($"constraint PK_{classe.SqlName} primary key (");
        }

        foreach (var pk in properties.Where(p => p.PrimaryKey))
        {
            ++pkCount;
            if (Config.TargetDBMS == TargetDBMS.Sqlserver)
            {
                sb.Append($"[{pk.SqlName}] ASC");
            }
            else
            {
                sb.Append(pk.SqlName);
            }

            if (pkCount < properties.Count(p => p.PrimaryKey))
            {
                sb.Append(", ");
            }
        }

        sb.Append(')');
    }

    /// <summary>
    /// Calcule la liste des déclarations de contraintes d'unicité.
    /// </summary>
    /// <param name="classe">Classe de la table.</param>
    /// <returns>Liste des déclarations de contraintes d'unicité.</returns>
    protected virtual IList<string> WriteUniqueKeyConstraints(Class classe)
    {
        var constraints = classe
            .Indexes.Where(idx => idx.Unique)
            .Select(idx =>
                Config.TargetDBMS == TargetDBMS.Sqlserver
                    ? $"constraint [{idx.SqlName}] unique nonclustered ({string.Join(", ", idx.Properties.Select(p => $"[{p.SqlName}] ASC"))})"
                    : $"constraint {idx.SqlName} unique ({string.Join(", ", idx.Properties.Select(p => $"{p.SqlName}"))})"
            )
            .ToList();

        return constraints;
    }
}
