<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>4.4.1</Version>
    <Description>Language Server TopModel.</Description>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>modls</ToolCommandName>
    <ResourceLanguages>en</ResourceLanguages>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OmniSharp.Extensions.LanguageServer" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TopModel.Core\TopModel.Core.csproj" />
    <ProjectReference Include="..\TopModel.Utils.Cli\TopModel.Utils.Cli.csproj" />
    <ProjectReference Include="..\TopModel.Utils.Mermaid\TopModel.Utils.Mermaid.csproj" />
  </ItemGroup>
</Project>
