<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>4.2.1</Version>
    <Description>Génération de diagrammes Mermaid pour TopModel.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TopModel.Core\TopModel.Core.csproj" />
  </ItemGroup>
</Project>
