<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Clients\TopModel.Sample.Clients.Db\TopModel.Sample.Clients.Db.csproj" />
    <ProjectReference Include="..\Clients\TopModel.Sample.Clients.External\TopModel.Sample.Clients.External.csproj" />
  </ItemGroup>
</Project>
