using System.Text;
using TopModel.Core.Model;
using TopModel.Generator.Core;
using TopModel.Utils;

namespace TopModel.Generator.Sql;

/// <summary>
/// Classe utilitaire pour écritre du SQL.
/// </summary>
public static class ScriptUtils
{
    public const string InsertKeyName = "InsertKey";

    public static IEnumerable<IProperty> GetAllProperties(this Class classe, IEnumerable<Class> availableClasses)
    {
        foreach (var prop in classe.Properties.Where(p => !p.AssociationMultiple))
        {
            yield return prop;
        }

        if (classe.ParentAssociationProperty != null)
        {
            yield return classe.ParentAssociationProperty!;
        }
    }

    /// <summary>
    /// Retourne la ligne d'insert pour une valeur.
    /// </summary>
    /// <param name="config">Config.</param>
    /// <param name="classe">Classe.</param>
    /// <param name="refValue">Item a insérer.</param>
    /// <returns>Requête.</returns>
    public static string GetInsertLine(this SqlConfig config, Class classe, ClassValue refValue)
    {
        var properties = new Dictionary<string, string?>();
        foreach (var property in classe.Properties)
        {
            if (refValue.Value.TryGetValue(property, out var value))
            {
                if (config.TranslateReferences == true && classe.DefaultProperty == property)
                {
                    properties[property.SqlName] =
                        $@"{(config.TargetDBMS == TargetDBMS.Sqlserver ? "N" : string.Empty)}'{refValue.ResourceKey}'";
                }
                else
                {
                    var val = config.GetValue(property, value);
                    properties[property.SqlName] = val == "null" ? "NULL" : val;
                }
            }
            else if (!property.AutoGeneratedValue)
            {
                properties[property.SqlName] = "NULL";
            }
        }

        // Création de la requête.
        var sb = new StringBuilder();
        sb.Append("INSERT INTO ").Append(classe.SqlName).Append('(');
        var isFirst = true;
        foreach (var columnName in properties.Keys)
        {
            if (!isFirst)
            {
                sb.Append(", ");
            }

            isFirst = false;
            sb.Append(columnName);
        }

        sb.Append(") VALUES(");

        isFirst = true;
        foreach (var value in properties.Values)
        {
            if (!isFirst)
            {
                sb.Append(", ");
            }

            isFirst = false;
            sb.Append(value);
        }

        sb.Append(");");
        return sb.ToString();
    }

    /// <summary>
    /// Retourne le nom du type de table SQL correspondant à la classe.
    /// </summary>
    /// <param name="classe">Classe.</param>
    /// <returns>Nom du type de table.</returns>
    public static string GetTableTypeName(this Class classe)
    {
        return classe == null ? throw new ArgumentNullException(nameof(classe)) : classe.SqlName + "_TABLE_TYPE";
    }

    public static IFileWriter OpenSqlWriter(this GeneratorBase<SqlConfig> generator, string fileName)
    {
        var fw = generator.OpenFileWriter(fileName);
        fw.StartCommentToken = "----";
        return fw;
    }

    public static void WriteComments(this IFileWriter writer, Class classe, SqlConfig config)
    {
        var tableName = config.CheckIdentifierLength(classe.SqlName);

        writer.WriteLine("/**");
        writer.WriteLine("  * Commentaires pour la table " + tableName);
        writer.WriteLine(" **/");

        if (config.TargetDBMS == TargetDBMS.Sqlserver)
        {
            writer.WriteLine(
                $"EXECUTE sp_addextendedproperty 'MS_Description', '{classe.Comment.Replace("'", "''")}', 'SCHEMA', 'dbo', 'TABLE', '{classe.SqlName}'"
            );
            writer.WriteLine("go");

            foreach (var p in classe.GetAllProperties(config.AvailableClasses))
            {
                writer.WriteLine(
                    $"EXECUTE sp_addextendedproperty 'MS_Description', '{p.Comment.Replace("'", "''")}', 'SCHEMA', 'dbo', 'TABLE', '{classe.SqlName}', 'COLUMN', '{p.SqlName}'"
                );
                writer.WriteLine("go");
            }
        }
        else
        {
            writer.WriteLine(
                $"COMMENT ON TABLE {tableName} IS '{classe.Comment.Replace("'", "''")}'{config.BatchSeparator}"
            );

            foreach (var p in classe.GetAllProperties(config.AvailableClasses))
            {
                writer.WriteLine(
                    $"COMMENT ON COLUMN {tableName}.{p.SqlName} IS '{p.Comment.Replace("'", "''")}'{config.BatchSeparator}"
                );
            }
        }
    }

    public static void WriteSqlFileHeader(
        this IFileWriter writer,
        string? appName = null,
        string? scriptName = null,
        string? description = null
    )
    {
        writer.WriteLine(
            "-- ==========================================================================================="
        );
        if (appName != null)
        {
            writer.WriteLine($"--   Application Name\t:\t{appName} ");
        }

        if (scriptName != null)
        {
            writer.WriteLine($"--   Script Name\t\t:\t{scriptName}");
        }

        if (description != null)
        {
            writer.WriteLine($"--   Description\t\t:\t{description}");
        }

        writer.WriteLine(
            "-- ==========================================================================================="
        );
    }
}
