#pragma warning disable KTA1200

using System.Text;
using TopModel.Core.Model;
using TopModel.Core.Utils;
using TopModel.Generator.Core;
using TopModel.Utils;

namespace TopModel.Generator.Sql;

/// <summary>
/// Classe utilitaire pour écrire du SQL.
/// </summary>
public static class ScriptUtils
{
    public const string InsertKeyName = "InsertKey";

    extension(Class classe)
    {
        public bool HasTable =>
            classe.IsPersistent
            && classe.Type != ClassType.Interface
            && (classe.Type != ClassType.Abstract || classe.InheritanceStrategy != InheritanceStrategy.DistinctTables)
            && (classe.Extends == null || classe.Extends.InheritanceStrategy != InheritanceStrategy.SingleTable);
    }

    /// <summary>
    /// Ecrit le SQL pour une colonne.
    /// </summary>
    /// <param name="config">Config.</param>
    /// <param name="writer">Writer.</param>
    /// <param name="classe">Clase.</param>
    /// <param name="property">Propriété.</param>
    public static void WriteColumn(this SqlConfig config, IFileWriter writer, Class classe, IProperty property)
    {
        var type =
            property is { Composition: null, Domain: not null } ? config.GetType(property)
            : property is { Composition: null, Domain: null } ? $"varchar({config.SqlIdentifierLengthLimit})"
            : config.TargetDBMS == TargetDBMS.Postgre ? "jsonb"
            : "json";

        writer.Write("\t");
        writer.Write(config.GetSqlName(property));
        writer.Write($" {type}");

        if (property.Required && !property.PrimaryKey && (property.Class == classe || property.Class.Extends != classe))
        {
            writer.Write(" not null");
        }

        if (
            property.Association == null
            && property.PrimaryKey
            && property.GeneratedValue != null
            && property.GeneratedValue.SequenceName == null
            && config.GetType(property).Contains("int")
            && (config.Ssdt == null || !config.Ssdt.DisableIdentity)
            && (classe.Extends == null || classe.Extends.InheritanceStrategy != InheritanceStrategy.DistinctTables)
        )
        {
            if (config.TargetDBMS == TargetDBMS.Sqlserver)
            {
                writer.Write($" identity");

                if (property.GeneratedValue.Start != 1 || property.GeneratedValue.Increment != 1)
                {
                    writer.Write($"({property.GeneratedValue.Start}, {property.GeneratedValue.Increment})");
                }
            }
            else
            {
                writer.Write(" generated by default as identity");
                if (property.GeneratedValue.Start != 1 || property.GeneratedValue.Increment != 1)
                {
                    writer.Write("(");
                    if (property.GeneratedValue.Start != 1)
                    {
                        writer.Write($"start with {property.GeneratedValue.Start}");
                    }

                    if (property.GeneratedValue.Increment != 1)
                    {
                        writer.Write(
                            $"{(property.GeneratedValue.Start != 1 ? " " : string.Empty)}increment by {property.GeneratedValue.Increment}"
                        );
                    }

                    writer.Write(")");
                }
            }
        }

        var defaultValue = config.GetValue(property);
        if (defaultValue != "null")
        {
            writer.Write($" default {defaultValue}");
        }
    }

    public static void WriteSequence(this SqlConfig config, IFileWriter writer, Class classe, string tag)
    {
        var classeForSequence =
            classe.Extends?.InheritanceStrategy != InheritanceStrategy.DistinctTables ? classe
            : classe.Extends.Type == ClassType.Abstract
            && config.Classes.Where(c => classe.Extends == c.Extends).OrderBy(c => c.SqlName).First() == classe
                ? classe.Extends
            : null;

        if (classeForSequence != null)
        {
            var pk = classeForSequence.PrimaryKey.FirstOrDefault();
            if (classeForSequence.PrimaryKey.Count() > 1 || pk?.Domain.GeneratedValue?.SequenceName == null)
            {
                return;
            }

            writer.WriteLine();
            writer.WriteLine("/**");
            writer.WriteLine(
                $"  * Création de la séquence pour la clé primaire de la table {config.GetSqlName(classeForSequence, noQuote: true)}"
            );
            writer.WriteLine(" **/");

            writer.Write($"create sequence {config.GetSequenceName(pk, tag)}");

            if (config.TargetDBMS != TargetDBMS.Oracle)
            {
                writer.Write($" as {config.GetType(pk)} ");
            }

            writer.Write(
                $"start with {pk.Domain.GeneratedValue!.Start} increment by {pk.Domain.GeneratedValue!.Increment}"
            );

            if (config.TargetDBMS == TargetDBMS.Oracle)
            {
                writer.Write("nocycle");
            }

            if (classeForSequence.HasTable && config.TargetDBMS == TargetDBMS.Postgre)
            {
                writer.Write($" owned by {config.GetSqlName(classeForSequence)}.{config.GetSqlName(pk)}");
            }

            writer.WriteLine(config.BatchSeparator);
        }
    }

    /// <summary>
    /// Retourne la ligne d'insert pour une valeur.
    /// </summary>
    /// <param name="config">Config.</param>
    /// <param name="classe">Classe.</param>
    /// <param name="refValue">Item a insérer.</param>
    /// <param name="tag">Tag.</param>
    /// <returns>Requête.</returns>
    public static string GetInsertLine(this SqlConfig config, Class classe, ClassValue refValue, string tag)
    {
        var properties = new Dictionary<string, string?>();
        foreach (var property in config.GetProperties(classe))
        {
            var insertValue = GetInsertValue(config, classe, property, refValue, tag);
            if (insertValue != null)
            {
                properties[config.GetSqlName(property)] = insertValue;
            }
        }

        // Création de la requête.
        var sb = new StringBuilder();
        sb.Append("INSERT INTO ").Append(config.GetSqlName(classe)).Append('(');
        var isFirst = true;
        foreach (var columnName in properties.Keys)
        {
            if (!isFirst)
            {
                sb.Append(", ");
            }

            isFirst = false;
            sb.Append(columnName);
        }

        sb.Append(") VALUES(");

        isFirst = true;
        foreach (var value in properties.Values)
        {
            if (!isFirst)
            {
                sb.Append(", ");
            }

            isFirst = false;
            sb.Append(value);
        }

        sb.Append(");");
        return sb.ToString();
    }

    public static IEnumerable<Class> SortInserts(this IEnumerable<Class> classes, SqlConfig config)
    {
        return CoreUtils.Sort(
            classes.OrderBy(c => c.SqlName),
            c =>
                config
                    .GetProperties(c)
                    .SelectMany(a => new[] { a.Association!, a.Association?.Extends! })
                    .Where(a => a != null && a != c && classes.Contains(a))
                    .Concat(c.Extends != null && c.Extends.Values.Count > 0 ? [c.Extends] : [])
        );
    }

    private static string? GetInsertValue(
        SqlConfig config,
        Class classe,
        IProperty property,
        ClassValue refValue,
        string tag
    )
    {
        if (
            refValue.Value.TryGetValue(
                classe.Extends != null && property.Association == classe.Extends
                    ? classe.Extends.PrimaryKey.Single()
                    : property,
                out var value
            )
        )
        {
            if (config.TranslateReferences == true && classe.DefaultProperty == property)
            {
                return $@"{(config.TargetDBMS == TargetDBMS.Sqlserver ? "N" : string.Empty)}'{refValue.ResourceKey}'";
            }

            var val = config.GetValue(property, value);
            return val == "null" ? "NULL" : val;
        }

        if (property.GeneratedValue != null && property.PrimaryKey)
        {
            return property.GeneratedValue.SequenceName != null ? config.GetNextValCall(property, tag) : null;
        }

        if (property == classe.DiscriminatorProperty && !classe.Properties.Contains(property))
        {
            return config.GetValue(property, refValue.Class.DiscriminatorValue ?? refValue.Class.SqlName);
        }

        return property.GeneratedValue != null ? null : "NULL";
    }

    public static IFileWriter OpenSqlWriter(this GeneratorBase<SqlConfig> generator, string fileName)
    {
        var fw = generator.OpenFileWriter(fileName);
        fw.StartCommentToken = "----";
        return fw;
    }

    public static void WriteComments(this IFileWriter writer, Class classe, SqlConfig config)
    {
        writer.WriteLine("/**");
        writer.WriteLine($"  * Commentaires pour la table {config.GetSqlName(classe, noQuote: true)}");
        writer.WriteLine(" **/");

        if (config.TargetDBMS == TargetDBMS.Sqlserver)
        {
            writer.WriteLine(
                $"EXECUTE sp_addextendedproperty 'MS_Description', '{classe.Comment.Replace("'", "''")}', 'SCHEMA', 'dbo', 'TABLE', '{config.GetSqlName(classe, noQuote: true)}'"
            );
            writer.WriteLine("go");

            foreach (var p in config.GetProperties(classe))
            {
                writer.WriteLine(
                    $"EXECUTE sp_addextendedproperty 'MS_Description', '{p.Comment.Replace("'", "''")}', 'SCHEMA', 'dbo', 'TABLE', '{config.GetSqlName(classe, noQuote: true)}', 'COLUMN', '{config.GetSqlName(p, noQuote: true)}'"
                );
                writer.WriteLine("go");
            }
        }
        else
        {
            writer.WriteLine(
                $"COMMENT ON TABLE {config.GetSqlName(classe)} IS '{classe.Comment.Replace("'", "''")}'{config.BatchSeparator}"
            );

            foreach (var p in config.GetProperties(classe))
            {
                writer.WriteLine(
                    $"COMMENT ON COLUMN {config.GetSqlName(classe)}.{config.GetSqlName(p)} IS '{p.Comment.Replace("'", "''")}'{config.BatchSeparator}"
                );
            }
        }
    }

    public static void WriteSqlFileHeader(
        this IFileWriter writer,
        string? appName = null,
        string? scriptName = null,
        string? description = null
    )
    {
        writer.WriteLine(
            "-- ==========================================================================================="
        );
        if (appName != null)
        {
            writer.WriteLine($"--   Application Name\t:\t{appName} ");
        }

        if (scriptName != null)
        {
            writer.WriteLine($"--   Script Name\t\t:\t{scriptName}");
        }

        if (description != null)
        {
            writer.WriteLine($"--   Description\t\t:\t{description}");
        }

        writer.WriteLine(
            "-- ==========================================================================================="
        );
    }
}
