using TopModel.Core.FileModel;

namespace TopModel.Core.Model;

public class ClassMappings
{
#nullable disable
    public bool To { get; set; }

    public LocatedString Name { get; set; }

    public Class Class { get; set; }

    public ClassReference ClassReference { get; set; }

    public bool Required { get; set; } = true;

#nullable enable
    public string? Comment { get; set; }

    public IDictionary<IProperty, IProperty> Mappings { get; } = new Dictionary<IProperty, IProperty>();

    public IDictionary<Reference, Reference> MappingReferences { get; } = new Dictionary<Reference, Reference>();

    public IEnumerable<IProperty> MissingRequiredProperties =>
        Class
            .Properties.Where(p =>
                p.Required
                && (
                    p
                    is ({ Composition: not null } or { DefaultValue: null })
                        and not { AssociationType: AssociationType.OneToMany or AssociationType.ManyToMany }
                )
                && !(p.Class.IsPersistent && p.PrimaryKey && p.Class.PrimaryKey.Count() == 1 && p.AutoGeneratedValue)
            )
            .Except(Mappings.Select(m => m.Value));
}
