using TopModel.Core.FileModel;

namespace TopModel.Core.Model;

public class ClassMappings
{
#nullable disable
    public bool To { get; set; }

    public LocatedString Name { get; set; }

    public Class Class { get; set; }

    public ClassReference ClassReference { get; set; }

    public bool Required { get; set; } = true;

#nullable enable
    public string? Comment { get; set; }

#pragma warning disable MA0016
    public Dictionary<IProperty, IProperty> Mappings { get; } = [];
#pragma warning restore MA0016

    public IDictionary<Reference, Reference> MappingReferences { get; } = new Dictionary<Reference, Reference>();

    public IEnumerable<IProperty> MissingRequiredProperties =>
        Class
            .Properties.Where(p =>
                p.Required
                && (
                    p
                    is (
                            CompositionProperty
                            or AliasProperty { Property: CompositionProperty }
                            or { DefaultValue: null }
                        )
                        and not AssociationProperty { Type: AssociationType.OneToMany or AssociationType.ManyToMany }
                )
                && !(
                    p.Class.IsPersistent
                    && p.PrimaryKey
                    && p.Class.PrimaryKey.Count() == 1
                    && p.Domain.AutoGeneratedValue
                )
            )
            .Except(Mappings.Select(m => m.Value));
}
