using TopModel.Core.FileModel;
using TopModel.Core.Model.Implementation;
using TopModel.Utils;

namespace TopModel.Core;

public class Domain
{
#nullable disable
    public LocatedString Name { get; set; }

    public string Label { get; set; }

    // Liste des converter pour lesquels le converter est présent dans la liste des domains From
    public HashSet<Converter> ConvertersFrom { get; set; } = new HashSet<Converter>();

    public HashSet<Converter> ConvertersTo { get; set; } = new HashSet<Converter>();

#nullable enable

    public int? Length { get; set; }

    public int? Scale { get; set; }

    public bool AutoGeneratedValue { get; set; }

    public bool BodyParam { get; set; }

    public Domain? ListDomain { get; set; }

    public DomainReference? ListDomainReference { get; set; }

    public DomainImplementation? CSharp { get; set; }

    public DomainImplementation? TS { get; set; }

    public DomainImplementation? Java { get; set; }

    public DomainImplementation? Sql { get; set; }

    public string? MediaType { get; set; }

    public string CSharpName => Name.Replace("DO_", string.Empty).ToPascalCaseStrict();

    public bool ShouldQuoteValue =>
        (Sql?.Type ?? string.Empty).Contains("varchar")
        || Sql?.Type == "text"
        || Sql?.Type == "uniqueidentifier"
        || Sql?.Type == "uuid"
        || (Sql?.Type ?? string.Empty).Contains("date")
        || (Sql?.Type ?? string.Empty).Contains("time")
        || CSharp?.Type == "string";

#nullable disable
    public ModelFile ModelFile { get; set; }

    internal Reference Location { get; set; }

    public override string ToString()
    {
        return Name;
    }
}