using TopModel.Core.FileModel;
using TopModel.Core.Model.Implementation;
using TopModel.Utils;

namespace TopModel.Core;

public class Domain
{
#nullable disable
    public LocatedString Name { get; set; }

    public string Label { get; set; }

    // Liste des converter pour lesquels le converter est présent dans la liste des domains From
    public HashSet<Converter> ConvertersFrom { get; set; } = new HashSet<Converter>();

    public HashSet<Converter> ConvertersTo { get; set; } = new HashSet<Converter>();

#nullable enable

    public int? Length { get; set; }

    public int? Scale { get; set; }

    public bool AutoGeneratedValue { get; set; }

    public bool BodyParam { get; set; }

    public Dictionary<string, Domain> AsDomains { get; set; } = [];

    public Dictionary<string, DomainReference> AsDomainReferences { get; set; } = [];

    public Dictionary<string, DomainImplementation> Implementations { get; set; } = [];

    public IList<TemplateParameter> TemplateParameters { get; set; } = [];

    public string? MediaType { get; set; }

    public bool IsMultipart => MediaType == "multipart/form-data";

    public string CSharpName => Name.Replace("DO_", string.Empty).ToPascalCase(true);

    public IEnumerable<ParameterReference> ParameterReferences => Implementations.Values
        .SelectMany(i =>
            (IEnumerable<ParameterReference>)[
                ..i.Type?.Parameters ?? [],
                ..i.GenericType?.Parameters ?? [],
                ..i.Annotations.SelectMany(a => a.Text.Parameters),
                ..i.Annotations.SelectMany(a => a.Imports.SelectMany(ai => ai.Parameters)),
                ..i.Imports.SelectMany(a => a.Parameters),
                ..i.ValueTemplates.Values.SelectMany(a => a.Value.Parameters),
                ..i.ValueTemplates.Values.SelectMany(a => a.Imports.SelectMany(vi => vi.Parameters))
            ])
        .Where(pr => pr.ReferenceName.IsValidPropertyVariable(TemplateParameters));

#nullable disable
    public ModelFile ModelFile { get; set; }

    internal Reference Location { get; set; }

    public override string ToString()
    {
        return Name;
    }
}