using TopModel.Core.FileModel;

namespace TopModel.Core.Model;

public interface IProperty : IAnnotationContainer
{
    string Name { get; }

    string NamePascal { get; }

    string NameCamel { get; }

    string NameByClassPascal { get; }

    string NameByClassCamel { get; }

    string SqlName { get; }

    string? Label { get; }

    bool PrimaryKey { get; }

    bool Required { get; }

    Domain Domain { get; }

    IDictionary<string, string> DomainParameters { get; }

    DomainReference? DomainReference { get; }

    string Comment { get; }

    string? DefaultValue { get; }

    bool Readonly { get; set; }

    LocatedString? Trigram { get; set; }

    string? FinalTrigram { get; }

    IDictionary<string, string> CustomProperties { get; }

    Class Class { get; set; }

    Endpoint Endpoint { get; set; }

    Decorator Decorator { get; set; }

    Decorator? SourceDecorator { get; set; }

    PropertyMapping PropertyMapping { get; set; }

    IPropertyContainer Parent =>
        Class ?? (IPropertyContainer)Endpoint ?? (IPropertyContainer)Decorator ?? PropertyMapping;

    IProperty ResourceProperty =>
        SourceDecorator != null ? SourceDecorator.Properties.First(p => p.Name == Name).ResourceProperty
        : this is AliasProperty alp && alp.Label == alp.OriginalProperty?.Label ? alp.OriginalProperty!.ResourceProperty
        : this;

    string ResourceKey =>
        $"{ResourceProperty.Parent.Namespace.ModuleCamel}.{ResourceProperty.Parent.NameCamel}.{ResourceProperty.NameCamel}";

    IProperty CommentResourceProperty =>
        SourceDecorator != null ? SourceDecorator.Properties.First(p => p.Name == Name).CommentResourceProperty
        : this is AliasProperty alp && alp.Comment == alp.OriginalProperty?.Comment
            ? alp.OriginalProperty!.CommentResourceProperty
        : this;

    string CommentResourceKey =>
        $"comments.{CommentResourceProperty.Parent.Namespace.ModuleCamel}.{CommentResourceProperty.Parent.NameCamel}.{CommentResourceProperty.NameCamel}";

    bool AutoGeneratedValue => Domain?.AutoGeneratedValue ?? false;

    bool UseLegacyRoleName { get; init; }

    IProperty CloneForDecorator(Class? classe = null, Endpoint? endpoint = null, Decorator? decorator = null);
}
