using TopModel.Core.FileModel;
using TopModel.Utils;

namespace TopModel.Core.Model;

public interface IProperty : IAnnotationContainer
{
    string Name { get; }

    string NamePascal => Parent.PreservePropertyCasing ? Name : TrueNamePascal;

    string NameCamel => Parent.PreservePropertyCasing ? Name : TrueNamePascal.ToFirstLower();

    string PropertyNamePascal => Parent.PreservePropertyCasing ? Name : TruePropertyNamePascal;

    string PropertyNameCamel => Parent.PreservePropertyCasing ? Name : TruePropertyNamePascal.ToFirstLower();

    string SqlName { get; }

    string? Label { get; }

    bool PrimaryKey { get; }

    bool Required { get; }

    Domain Domain { get; }

    IDictionary<string, string> DomainParameters { get; }

    DomainReference? DomainReference { get; }

    string Comment { get; }

    string? DefaultValue { get; }

    bool Readonly { get; set; }

    LocatedString? Trigram { get; set; }

    string? FinalTrigram { get; }

    IDictionary<string, string> CustomProperties { get; }

    Class Class { get; set; }

    Endpoint Endpoint { get; set; }

    Decorator Decorator { get; set; }

    IProperty? SourceProperty { get; }

    IPropertyContainer? SourceContainer => SourceProperty?.Parent;

    PropertyMapping PropertyMapping { get; set; }

    IPropertyContainer Parent =>
        Class ?? (IPropertyContainer)Endpoint ?? (IPropertyContainer)Decorator ?? PropertyMapping;

    IProperty ResourceProperty =>
        SourceContainer != null ? SourceContainer.Properties.First(p => p.Name == Name).ResourceProperty
        : this is AliasProperty alp && alp.Label == alp.OriginalProperty?.Label ? alp.OriginalProperty!.ResourceProperty
        : this;

    string ResourceKey =>
        $"{ResourceProperty.Parent.Namespace.ModuleCamel}.{ResourceProperty.Parent.NameCamel}.{ResourceProperty.PropertyNameCamel}";

    IProperty CommentResourceProperty =>
        SourceContainer != null ? SourceContainer.Properties.First(p => p.Name == Name).CommentResourceProperty
        : this is AliasProperty alp && alp.Comment == alp.OriginalProperty?.Comment
            ? alp.OriginalProperty!.CommentResourceProperty
        : this;

    string CommentResourceKey =>
        $"comments.{CommentResourceProperty.Parent.Namespace.ModuleCamel}.{CommentResourceProperty.Parent.NameCamel}.{CommentResourceProperty.PropertyNameCamel}";

    [Obsolete("Utiliser `GeneratedValue` à la place.")]
    bool AutoGeneratedValue => Domain?.GeneratedValue != null;

    GeneratedValueDefinition? GeneratedValue => this.Association == null ? Domain?.GeneratedValue : null;

    internal string TrueNamePascal { get; }

    internal string TruePropertyNamePascal { get; }

    IProperty CloneDefinition();

    IProperty CloneForContainer(IPropertyContainer container);
}
