using TopModel.Core.FileModel;

namespace TopModel.Core;

public class RegularProperty : IFieldProperty
{
#nullable disable
    public string Name { get; set; }
#nullable enable

    public string? Label { get; set; }

    public bool PrimaryKey { get; set; }

    public bool Required { get; set; }

    public LocatedString? Trigram { get; set; }

#nullable disable
    public Domain Domain { get; set; }

    public string Comment { get; set; }

    public Class Class { get; set; }

    public Endpoint Endpoint { get; set; }

    public Decorator Decorator { get; set; }

    public DomainReference DomainReference { get; set; }

#nullable enable

    public string? DefaultValue { get; set; }

#nullable disable

    public bool ReferenceKey =>
        ((Class?.Reference ?? false) || (Class?.ReferenceValues.Any() ?? false)) && Class.PrimaryKey?.Domain.AutoGeneratedValue != true
        && this == (Class.PrimaryKey ?? Class.Properties.OfType<IFieldProperty>().First());

    public bool UseLegacyRoleName { get; init; }

    internal Reference Location { get; set; }

    public IProperty CloneWithClass(Class classe)
    {
        return new RegularProperty
        {
            Class = classe,
            Comment = Comment,
            Decorator = Decorator,
            DefaultValue = DefaultValue,
            Domain = Domain,
            Label = Label,
            Location = Location,
            Name = Name,
            PrimaryKey = PrimaryKey,
            Required = Required
        };
    }
}