using Microsoft.Extensions.Logging;
using TopModel.Generator.Ssdt;

namespace TopModel.Generator.ProceduralSql;

/// <summary>
/// Générateur de PL-SQL.
/// </summary>
public class PostgreSchemaGenerator : AbstractSchemaGenerator
{
    private ProceduralSqlConfig _config;

    public PostgreSchemaGenerator(ProceduralSqlConfig config, ILogger<ProceduralSqlGenerator> logger)
        : base(config, logger)
    {
        this._config = config;
    }

    protected override string BatchSeparator => ";";

    protected override bool SupportsClusteredKey => false;

    protected override bool UseQuotes => false;

    /// <summary>
    /// Gère l'auto-incrémentation des clés primaires en ajoutant identity à la colonne.
    /// </summary>
    /// <param name="writerCrebas">Flux d'écriture création bases.</param>
    protected override void WriteIdentityColumn(SqlFileWriter writerCrebas)
    {
        writerCrebas.Write(" generated by default as identity");
        if (this._config.IdentityIncrement != null || this._config.IdentityStart != null)
        {
            writerCrebas.Write(" (");
            if (this._config.IdentityStart != null)
            {
                writerCrebas.Write($"{$"start with {this._config.IdentityStart}"}");
            }

            if (this._config.IdentityIncrement != null)
            {
                writerCrebas.Write($"{$" increment {this._config.IdentityIncrement}"}");
            }

            writerCrebas.Write(")");
        }
    }
}