name: modgen --check

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: demo
          POSTGRES_USER: demo
          POSTGRES_DB: demo
        ports:
          - 5962:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      - name: build
        run: dotnet build

      - name: tmdgen (tests)
        run: dotnet run --project TopModel.ModelGenerator/TopModel.ModelGenerator.csproj -- -f tests/tmdgen/open-api/tmdgen.config -c

      - name: modgen (tests)
        run: dotnet run --project ../TopModel.Generator/TopModel.Generator.csproj -- -c
        working-directory: tests

      - name: modgen (tuto)
        run: dotnet run --project ../TopModel.Generator/TopModel.Generator.csproj -- -c
        working-directory: docs

      - name: build C# sample
        run: dotnet build
        working-directory: tests/output/csharp/src

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven

      - name: Init database
        run: |
          for f in tests/output/pg/src/*.sql; do
            PGPASSWORD=demo psql -h localhost -p 5962 -U demo -d demo -f "$f"
          done

      - name: build jpa samples
        run: mvn test
        working-directory: ./tests/output/jpa

      - name: Set up node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: deps sample angular
        run: npm ci
        working-directory: ./tests/output/angular
      - name: build sample angular
        run: npm run build
        working-directory: ./tests/output/angular

      - name: deps sample focus
        run: npm ci
        working-directory: ./tests/output/focus
      - name: build sample focus
        run: npm run build
        working-directory: ./tests/output/focus

      - name: deps sample vanilla-js
        run: npm i -g typescript
        working-directory: ./tests/output/vanilla-js
      - name: build sample vanilla-js
        run: tsc --noEmit
        working-directory: ./tests/output/vanilla-js
