name: Test coverage
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test coverage
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: run tests
        run: dotnet-coverage collect --output "./modgen-coverage-results.xml" --output-format cobertura -- "dotnet run --project ./TopModel.Generator -c Release"
      - name: run tests
        run: dotnet-coverage collect --output "./tmdgen-coverage-results.xml" --output-format cobertura -- "dotnet run --project TopModel.ModelGenerator/TopModel.ModelGenerator.csproj -- -f tests/tmdgen/open-api/tmdgen.config -c"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage-results.xml
